"""Update datetime field in user model into the database

Revision ID: 76849cd431ce
Revises: 5e45ac4139fe
Create Date: 2024-05-02 19:57:00.319738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76849cd431ce'
down_revision: Union[str, None] = '5e45ac4139fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
