"""Update datetime field in user model

Revision ID: 5e45ac4139fe
Revises: 01705eb5c828
Create Date: 2024-05-02 19:49:54.856965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e45ac4139fe'
down_revision: Union[str, None] = '01705eb5c828'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
